# Generated by Django 5.1.3 on 2024-11-15 09:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='day',
            name='date',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rep',
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2024, 11, 15, 9, 30, 35, 543638))),
                ('rep', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.exercise')),
            ],
        ),
    ]
